#!/usr/bin/env python3
"""Consent-based receive-only file collector for Android/Termux.

The server accepts chunks only for paths present in a manifest generated by the
operator. It never reads from the PS4, executes uploaded files, or exposes a
filesystem browsing endpoint.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import secrets
import tempfile
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse

MAX_CHUNK = 1024 * 1024


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


class CollectorState:
    def __init__(self, root: Path, token: str, manifest_path: Path):
        self.root = root.resolve()
        self.token = token
        self.manifest_path = manifest_path
        self.manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        self.entries = {e["id"]: e for e in self.manifest.get("files", [])}
        self.root.mkdir(parents=True, exist_ok=True)
        (self.root / ".parts").mkdir(exist_ok=True)
        self.status = {}

    def entry(self, file_id: str):
        return self.entries.get(file_id)

    def part_path(self, file_id: str, offset: int) -> Path:
        return self.root / ".parts" / f"{file_id}.{offset}.part"

    def final_path(self, entry: dict) -> Path:
        rel = Path(entry["destination"])
        if rel.is_absolute() or ".." in rel.parts:
            raise ValueError("manifest destination must be relative")
        return (self.root / rel).resolve()

    def record(self, file_id: str, state: str, **extra):
        self.status[file_id] = {"state": state, **extra}
        (self.root / "collector-status.json").write_text(
            json.dumps(self.status, indent=2, sort_keys=True), encoding="utf-8"
        )


class Handler(BaseHTTPRequestHandler):
    server_version = "PS4Collector/1.0"

    def authorized(self) -> bool:
        supplied = self.headers.get("Authorization", "")
        return secrets.compare_digest(supplied, f"Bearer {self.server.state.token}")

    def send_json(self, code: int, data: dict):
        raw = json.dumps(data, sort_keys=True).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def do_GET(self):
        if not self.authorized():
            self.send_json(401, {"error": "unauthorized"})
            return
        parsed = urlparse(self.path)
        if parsed.path == "/v1/manifest":
            self.send_json(200, self.server.state.manifest)
        elif parsed.path == "/v1/status":
            self.send_json(200, self.server.state.status)
        else:
            self.send_json(404, {"error": "not found"})

    def do_POST(self):
        if not self.authorized():
            self.send_json(401, {"error": "unauthorized"})
            return
        parsed = urlparse(self.path)
        if parsed.path != "/v1/finalize":
            self.send_json(404, {"error": "not found"})
            return
        file_id = parse_qs(parsed.query).get("id", [""])[0]
        entry = self.server.state.entry(file_id)
        if not entry:
            self.send_json(403, {"error": "file id is not allowlisted"})
            return
        size = int(entry["size"])
        final = self.server.state.final_path(entry)
        final.parent.mkdir(parents=True, exist_ok=True)
        tmp = Path(tempfile.mkstemp(prefix=f".{file_id}.", dir=str(final.parent))[1])
        try:
            with tmp.open("wb") as out:
                offset = 0
                while offset < size:
                    part = self.server.state.part_path(file_id, offset)
                    if not part.exists() or part.stat().st_size > MAX_CHUNK:
                        self.server.state.record(file_id, "incomplete", missing_offset=offset)
                        self.send_json(409, {"error": "missing chunk", "offset": offset})
                        return
                    data = part.read_bytes()
                    if not data or offset + len(data) > size:
                        self.send_json(422, {"error": "invalid stored chunk", "offset": offset})
                        return
                    out.write(data)
                    offset += len(data)
            actual = sha256_file(tmp)
            if actual != entry["sha256"] or tmp.stat().st_size != size:
                self.server.state.record(file_id, "hash_mismatch", actual_sha256=actual)
                self.send_json(422, {"error": "file hash mismatch", "actual": actual})
                return
            os.replace(tmp, final)
            self.server.state.record(file_id, "complete", size=size, sha256=actual, destination=str(final))
            self.send_json(200, {"ok": True, "id": file_id, "size": size, "sha256": actual})
        finally:
            if tmp.exists(): tmp.unlink()

    def do_PUT(self):
        if not self.authorized():
            self.send_json(401, {"error": "unauthorized"})
            return
        parsed = urlparse(self.path)
        if parsed.path != "/v1/chunk":
            self.send_json(404, {"error": "not found"})
            return
        q = parse_qs(parsed.query)
        file_id = q.get("id", [""])[0]
        try:
            offset = int(q.get("offset", ["-1"])[0])
            length = int(q.get("length", ["-1"])[0])
        except ValueError:
            self.send_json(400, {"error": "invalid offset/length"})
            return
        entry = self.server.state.entry(file_id)
        if not entry:
            self.send_json(403, {"error": "file id is not allowlisted"})
            return
        expected_size = int(entry["size"])
        if offset < 0 or length <= 0 or length > MAX_CHUNK or offset + length > expected_size:
            self.send_json(400, {"error": "invalid chunk bounds"})
            return
        body = self.rfile.read(length)
        if len(body) != length:
            self.send_json(400, {"error": "short body"})
            return
        claimed = self.headers.get("X-Chunk-SHA256", "")
        actual = hashlib.sha256(body).hexdigest()
        if claimed != actual:
            self.send_json(422, {"error": "chunk hash mismatch", "actual": actual})
            return
        part = self.server.state.part_path(file_id, offset)
        part.write_bytes(body)
        self.server.state.record(file_id, "receiving", last_offset=offset, length=length)
        self.send_json(200, {"ok": True, "id": file_id, "offset": offset, "sha256": actual})

    def log_message(self, fmt, *args):
        print(f"[{self.address_string()}] {fmt % args}")


class Server(ThreadingHTTPServer):
    def __init__(self, addr, state):
        super().__init__(addr, Handler)
        self.state = state


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bind", default="0.0.0.0")
    ap.add_argument("--port", type=int, default=8787)
    ap.add_argument("--root", required=True)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--token", required=True)
    args = ap.parse_args()
    state = CollectorState(Path(args.root), args.token, Path(args.manifest))
    print(f"Listening on http://{args.bind}:{args.port}; receive-only mode")
    Server((args.bind, args.port), state).serve_forever()


if __name__ == "__main__":
    main()
